const TEAM_NAMES_RU = {
  'Arsenal': 'Арсенал',
  'Chelsea': 'Челси',
  'Liverpool': 'Ливерпуль',
  'Manchester City': 'Манчестер Сити',
  'Manchester United': 'Манчестер Юнайтед',
  'Tottenham': 'Тоттенхэм',
  'Tottenham Hotspur': 'Тоттенхэм',
  'Newcastle': 'Ньюкасл',
  'Newcastle United': 'Ньюкасл',
  'Aston Villa': 'Астон Вилла',
  'West Ham': 'Вест Хэм',
  'West Ham United': 'Вест Хэм',
  'Brighton': 'Брайтон',
  'Brighton & Hove Albion': 'Брайтон',
  'Brentford': 'Брентфорд',
  'Fulham': 'Фулхэм',
  'Crystal Palace': 'Кристал Пэлас',
  'Everton': 'Эвертон',
  'Wolverhampton': 'Вулверхэмптон',
  'Wolverhampton Wanderers': 'Вулверхэмптон',
  'Nottingham Forest': 'Ноттингем Форест',
  'Nottm Forest': 'Ноттингем Форест',
  'Leicester': 'Лестер',
  'Leicester City': 'Лестер',
  'Southampton': 'Саутгемптон',
  'Ipswich': 'Ипсвич',
  'Ipswich Town': 'Ипсвич',
  'Bournemouth': 'Борнмут',
  'AFC Bournemouth': 'Борнмут',
  'Leeds': 'Лидс',
  'Leeds United': 'Лидс',
  'Burnley': 'Бёрнли',
  'Sheffield United': 'Шеффилд Юнайтед',
  'Luton': 'Лутон',
  'Luton Town': 'Лутон',
  'Sunderland': 'Сандерленд',
  'Watford': 'Уотфорд',
  'Norwich City': 'Норвич',
  'Real Madrid': 'Реал Мадрид',
  'Barcelona': 'Барселона',
  'Atletico Madrid': 'Атлетико Мадрид',
  'Atlético Madrid': 'Атлетико Мадрид',
  'Sevilla': 'Севилья',
  'Valencia': 'Валенсия',
  'Villarreal': 'Вильярреал',
  'Real Sociedad': 'Реал Сосьедад',
  'Athletic Bilbao': 'Атлетик Бильбао',
  'Athletic Club': 'Атлетик Бильбао',
  'Betis': 'Бетис',
  'Real Betis': 'Бетис',
  'Osasuna': 'Осасуна',
  'Girona': 'Жирона',
  'Mallorca': 'Мальорка',
  'Las Palmas': 'Лас-Пальмас',
  'Rayo Vallecano': 'Райо Вальекано',
  'Getafe': 'Хетафе',
  'Celta Vigo': 'Сельта',
  'Celta de Vigo': 'Сельта',
  'Espanol': 'Эспаньол',
  'Espanyol': 'Эспаньол',
  'Valladolid': 'Вальядолид',
  'Real Valladolid': 'Вальядолид',
  'Leganes': 'Леганес',
  'CD Leganes': 'Леганес',
  'Bayern Munich': 'Бавария',
  'Bayern München': 'Бавария',
  'Borussia Dortmund': 'Боруссия Дортмунд',
  'Bayer Leverkusen': 'Байер Леверкузен',
  'RB Leipzig': 'РБ Лейпциг',
  'Eintracht Frankfurt': 'Айнтрахт Франкфурт',
  'VfL Wolfsburg': 'Вольфсбург',
  'Wolfsburg': 'Вольфсбург',
  'Borussia Monchengladbach': 'Боруссия Мёнхенгладбах',
  'Borussia Mönchengladbach': 'Боруссия Мёнхенгладбах',
  'Union Berlin': 'Унион Берлин',
  '1. FC Union Berlin': 'Унион Берлин',
  'Freiburg': 'Фрайбург',
  'SC Freiburg': 'Фрайбург',
  'Hoffenheim': 'Хоффенхайм',
  'TSG Hoffenheim': 'Хоффенхайм',
  'Mainz': 'Майнц',
  'FSV Mainz 05': 'Майнц',
  '1. FSV Mainz 05': 'Майнц',
  'Werder Bremen': 'Вердер',
  'Augsburg': 'Аугсбург',
  'FC Augsburg': 'Аугсбург',
  'Stuttgart': 'Штутгарт',
  'VfB Stuttgart': 'Штутгарт',
  'Koln': 'Кёльн',
  'Cologne': 'Кёльн',
  '1. FC Köln': 'Кёльн',
  'Heidenheim': 'Хайденхайм',
  '1. FC Heidenheim': 'Хайденхайм',
  'Bochum': 'Бохум',
  'VfL Bochum': 'Бохум',
  'Schalke': 'Шальке',
  'FC Schalke 04': 'Шальке',
  'St. Pauli': 'Санкт Паули',
  'FC St. Pauli': 'Санкт Паули',
  'Hamburger SV': 'Гамбург',
  'Holstein Kiel': 'Кёль Киль',
  'Juventus': 'Ювентус',
  'Inter': 'Интер',
  'Inter Milan': 'Интер',
  'AC Milan': 'Милан',
  'Milan': 'Милан',
  'Napoli': 'Наполи',
  'Roma': 'Рома',
  'AS Roma': 'Рома',
  'Lazio': 'Лацио',
  'SS Lazio': 'Лацио',
  'Atalanta': 'Аталанта',
  'Fiorentina': 'Фиорентина',
  'ACF Fiorentina': 'Фиорентина',
  'Torino': 'Торино',
  'Bologna': 'Болонья',
  'Udinese': 'Удинезе',
  'Cagliari': 'Кальяри',
  'Hellas Verona': 'Верона',
  'Verona': 'Верона',
  'Empoli': 'Эмполи',
  'Lecce': 'Лечче',
  'US Lecce': 'Лечче',
  'Monza': 'Монца',
  'Venezia': 'Венеция',
  'Genoa': 'Дженоа',
  'Como': 'Комо',
  'Como 1907': 'Комо',
  'Parma': 'Парма',
  'Paris Saint-Germain': 'ПСЖ',
  'PSG': 'ПСЖ',
  'Marseille': 'Марсель',
  'Olympique Marseille': 'Марсель',
  'Lyon': 'Лион',
  'Olympique Lyonnais': 'Лион',
  'Monaco': 'Монако',
  'AS Monaco': 'Монако',
  'Lille': 'Лилль',
  'LOSC Lille': 'Лилль',
  'Nice': 'Ницца',
  'OGC Nice': 'Ницца',
  'Rennes': 'Ренн',
  'Stade Rennais': 'Ренн',
  'Lens': 'Ланс',
  'RC Lens': 'Ланс',
  'Strasbourg': 'Страсбур',
  'Montpellier': 'Монпелье',
  'Nantes': 'Нант',
  'Brest': 'Брест',
  'Stade Brestois': 'Брест',
  'Reims': 'Реймс',
  'Stade de Reims': 'Реймс',
  'Toulouse': 'Тулуза',
  'Angers': 'Анже',
  'Saint-Etienne': 'Сент-Этьен',
  'AS Saint-Etienne': 'Сент-Этьен',
  'Auxerre': 'Осер',
  'AJ Auxerre': 'Осер',
  'Ajax': 'Аякс',
  'AFC Ajax': 'Аякс',
  'PSV': 'ПСВ',
  'PSV Eindhoven': 'ПСВ',
  'Feyenoord': 'Фейеноорд',
  'AZ Alkmaar': 'АЗ',
  'AZ': 'АЗ',
  'Twente': 'Твенте',
  'FC Twente': 'Твенте',
  'Benfica': 'Бенфика',
  'SL Benfica': 'Бенфика',
  'Porto': 'Порту',
  'FC Porto': 'Порту',
  'Sporting CP': 'Спортинг',
  'Sporting': 'Спортинг',
  'Braga': 'Брага',
  'SC Braga': 'Брага',
  'Celtic': 'Селтик',
  'Rangers': 'Рейнджерс',
  'Galatasaray': 'Галатасарай',
  'Fenerbahce': 'Фенербахче',
  'Fenerbahçe': 'Фенербахче',
  'Besiktas': 'Бешикташ',
  'Beşiktaş': 'Бешикташ',
  'Trabzonspor': 'Трабзонспор',
  'Zenit': 'Зенит',
  'Zenit St Petersburg': 'Зенит',
  'CSKA Moscow': 'ЦСКА',
  'PFC CSKA Moscow': 'ЦСКА',
  'Spartak Moscow': 'Спартак',
  'Lokomotiv Moscow': 'Локомотив',
  'Dinamo Moscow': 'Динамо',
  'FK Dynamo Moscow': 'Динамо',
  'Krasnodar': 'Краснодар',
  'FK Krasnodar': 'Краснодар',
  'Rubin Kazan': 'Рубин',
  'Rostov': 'Ростов',
  'FK Rostov': 'Ростов',
  'Akhmat Grozny': 'Ахмат',
  'Sochi': 'Сочи',
  'FK Sochi': 'Сочи',
  'Krylya Sovetov': 'Крылья Советов',
  'Fakel Voronezh': 'Факел',
  'Orenburg': 'Оренбург',
  'FK Orenburg': 'Оренбург',
  'Nizhny Novgorod': 'Нижний Новгород',
  'Pari Nizhny Novgorod': 'Нижний Новгород',
  'Torpedo Moscow': 'Торпедо',
  'Shakhtar Donetsk': 'Шахтёр',
  'Shakhtar': 'Шахтёр',
  'Dynamo Kyiv': 'Динамо Киев',
  'Dinamo Zagreb': 'Динамо Загреб',
  'GNK Dinamo': 'Динамо Загреб',
  'Red Bull Salzburg': 'Зальцбург',
  'FC Red Bull Salzburg': 'Зальцбург',
  'Salzburg': 'Зальцбург',
  'Club Brugge': 'Брюгге',
  'Club Brugge KV': 'Брюгге',
  'Anderlecht': 'Андерлехт',
  'RSC Anderlecht': 'Андерлехт',
  'Young Boys': 'Янг Бойз',
  'BSC Young Boys': 'Янг Бойз',
  'Viktoria Plzen': 'Виктория Пльзень',
  'Slavia Prague': 'Славия Прага',
  'SK Slavia Prague': 'Славия Прага',
  'Sparta Prague': 'Спарта Прага',
  'AC Sparta Prague': 'Спарта Прага',
  'Olympiacos': 'Олимпиакос',
  'PAOK': 'ПАОК',
  'Ferencvaros': 'Ференцварош',
  'Ferencváros': 'Ференцварош',
  'Maccabi Tel Aviv': 'Маккаби ТА',
  'Maccabi Haifa': 'Маккаби Хайфа',
  'Flamengo': 'Фламенго',
  'CR Flamengo': 'Фламенго',
  'Fluminense': 'Флуминенсе',
  'Palmeiras': 'Палмейрас',
  'SE Palmeiras': 'Палмейрас',
  'Corinthians': 'Коринтианс',
  'Gremio': 'Гремио',
  'Grêmio': 'Гремио',
  'Internacional': 'Интернасьонал',
  'Atletico Mineiro': 'Атлетико Минейро',
  'Atlético Mineiro': 'Атлетико Минейро',
  'Botafogo': 'Ботафого',
  'Sao Paulo': 'Сан-Паулу',
  'São Paulo': 'Сан-Паулу',
  'Cruzeiro': 'Крузейро',
  'Boca Juniors': 'Бока Хуниорс',
  'River Plate': 'Ривер Плейт',
  'Inter Miami': 'Интер Майами',
  'Inter Miami CF': 'Интер Майами',
  'LA Galaxy': 'ЛА Гэлакси',
}

function translateTeam(name) {
  if (!name) return name
  const key = (name || '').trim().replace(/\s+/g, ' ')
  return TEAM_NAMES_RU[key] || name
}

module.exports = { translateTeam }
